### ISSUE TITLE
break up lib into separate files

### ISSUE THREAD

**Issue by cullophid** [cullophid/barely-functional#8]
Taking a page out of https://github.com/1-liners/1-liners playbook.

This means that we don't have to worry about feature creeping and bloat, and users only need to import what they need.

Im interested in hearing what people think?

**Comment by svozza** [comment]
Yep, this would be pretty sweet. Users could just do `require(barely-function/map)` or whatever.

**Comment by cullophid** [comment]
It would be a rewrite though

**Comment by svozza** [comment]
That's fine. Do we need to do anything to enable the `require('barely-functional/map')`. If we put all the source files in a folder that would change the path to `require('barely-functional/<folderName>/map`, which isn't nearly as nice.

**Comment by cullophid** [comment]
no we just need to put the files in the root.

**Comment by svozza** [comment]
Cool. Do we still export all the functions in an `index.js` file?

**Comment by cullophid** [comment]
Yes. Have a look at the 1-liners library

**Comment by svozza** [comment]
So I think this is all finally done pending the merging of #25. @cullophid we should do a release to NPM now.

**Comment by rickmed** [comment]
I'm interested in this npm release too @cullophid
